"""empty message

Revision ID: 1430287058fa
Revises: 17e379942491
Create Date: 2020-11-14 22:23:06.266352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1430287058fa'
down_revision = '17e379942491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('form_result_fkey', 'form', type_='foreignkey')
    op.drop_column('form', 'result')
    op.add_column('form_template', sa.Column('label', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_template', 'label')
    op.add_column('form', sa.Column('result', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('form_result_fkey', 'form', 'result', ['result'], ['id'])
    # ### end Alembic commands ###
