"""empty message

Revision ID: 28b14d52bd7c
Revises: 8dfa03c04ad0
Create Date: 2020-11-16 11:57:43.238614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28b14d52bd7c'
down_revision = '8dfa03c04ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('form_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'answer', 'form', ['form_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.drop_column('answer', 'form_id')
    # ### end Alembic commands ###
