"""empty message

Revision ID: 7650ccb2856b
Revises: e6dd49515a04
Create Date: 2020-11-07 19:04:07.356206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7650ccb2856b'
down_revision = 'e6dd49515a04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('form', 'template_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('form', 'template_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
