"""empty message

Revision ID: 8bbed431de9d
Revises: 
Create Date: 2020-11-19 23:07:28.533468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bbed431de9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'question_order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('question_order', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
