"""empty message

Revision ID: 8dfa03c04ad0
Revises: 
Create Date: 2020-11-15 22:21:39.099354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dfa03c04ad0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('filler_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['filler_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'filler_id')
    )
    op.drop_table('grade')
    op.drop_table('result')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('result_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('form_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['form.id'], name='result_form_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='result_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('grade',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('result_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['result.id'], name='grade_result_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='grade_pkey')
    )
    op.drop_table('answer')
    # ### end Alembic commands ###
