"""empty message

Revision ID: 9a227fa5aa16
Revises: d0e01c64c004
Create Date: 2020-10-22 18:03:16.230622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a227fa5aa16'
down_revision = 'd0e01c64c004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_template_question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_template_question',
    sa.Column('template_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name='form_template_question_question_id_fkey'),
    sa.ForeignKeyConstraint(['template_id'], ['form_template.id'], name='form_template_question_template_id_fkey'),
    sa.PrimaryKeyConstraint('question_id', name='form_template_question_pkey')
    )
    # ### end Alembic commands ###
