"""empty message

Revision ID: a6b614e43240
Revises: d8fb025bba00
Create Date: 2020-11-10 23:01:59.195372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b614e43240'
down_revision = 'd8fb025bba00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_template', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'form_template', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'form_template', type_='foreignkey')
    op.drop_column('form_template', 'user_id')
    # ### end Alembic commands ###
