"""empty message

Revision ID: ab6d116fd68e
Revises: 9a227fa5aa16
Create Date: 2020-10-22 18:04:51.739760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab6d116fd68e'
down_revision = '9a227fa5aa16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('template_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'question', 'form_template', ['template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'template_id')
    # ### end Alembic commands ###
