"""empty message

Revision ID: e6dd49515a04
Revises: ab6d116fd68e
Create Date: 2020-10-22 18:40:12.874988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6dd49515a04'
down_revision = 'ab6d116fd68e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_template', sa.Column('visible', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_template', 'visible')
    # ### end Alembic commands ###
